{% set name = "kubernetes-kind" %}
{% set version = "0.23.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url:  https://github.com/kubernetes-sigs/kind/archive/v{{ version }}.tar.gz
  sha256: b8ea6665bc37a34de0a6fe7592fb8ae376847e1c93fc5d6377140a98c1aa6a55

build:
  skip: True  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  requires:
    - ripgrep
  commands:
    - kind --help
    - kind --version | rg {{ version }}

about:
  summary: Kubernetes IN Docker - local clusters for testing Kubernetes
  home: https://github.com/kubernetes-sigs/kind
  license:  Apache-2.0
  license_file:
    - LICENSE
    - thirdparty/

extra:
  recipe-maintainers:
    - dhirschfeld
